name: Sync to OSS with Zero Downtime

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and build
        run: |
          npm install
          npm run docs:build

      - name: Install ossutil
        run: |
          curl -L https://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64 -o /usr/local/bin/ossutil
          chmod +x /usr/local/bin/ossutil

      - name: Generate unique deployment directory
        id: deployment
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "DEPLOY_DIR=deploy-$TIMESTAMP" >> $GITHUB_ENV

      - name: Upload new version to temp directory
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_SECRET }}
        run: |
          ossutil cp -r ./docs/.vuepress/dist/ oss://fromidea/$DEPLOY_DIR/ \
            --access-key-id=$ACCESS_KEY_ID \
            --access-key-secret=$ACCESS_KEY_SECRET \
            --endpoint=oss-cn-hangzhou.aliyuncs.com \
            --update

      - name: Update OSS routing configuration (atomic switch)
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_SECRET }}
        run: |
          # 1. Upload a new index.html that redirects to the new version
          echo "<!DOCTYPE html><html><head><meta http-equiv=\"refresh\" content=\"0; url=/$DEPLOY_DIR/index.html\" /></head></html>" > index.html
          ossutil cp index.html oss://fromidea/index.html \
            --access-key-id=$ACCESS_KEY_ID \
            --access-key-secret=$ACCESS_KEY_SECRET \
            --endpoint=oss-cn-hangzhou.aliyuncs.com

          # 2. Alternatively, if using OSS static website hosting with routing rules:
          # You can configure OSS to serve the new version directly

      - name: Clean up old deployments (safely exclude current)
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_SECRET }}
        run: |
          # 获取所有部署目录（按时间倒序）
          ossutil ls oss://fromidea/ \
            --access-key-id=$ACCESS_KEY_ID \
            --access-key-secret=$ACCESS_KEY_SECRET \
            --endpoint=oss-cn-hangzhou.aliyuncs.com | \
            grep -o "oss://fromidea/deploy-[0-9]*" | \
            sort -r > all_deploys.txt

          # 读取当前部署目录（从环境变量）
          echo "Current deploy: $DEPLOY_DIR"

          # 排除当前版本后，取第6个及以后的旧版本
          grep -v "deploy-$DEPLOY_DIR$" all_deploys.txt | \
            tail -n +6 | \
            xargs -I {} sh -c '
              echo "Deleting old deploy: {}";
              ossutil rm -rf {} \
                --access-key-id=$ACCESS_KEY_ID \
                --access-key-secret=$ACCESS_KEY_SECRET \
                --endpoint=oss-cn-hangzhou.aliyuncs.com
            ' || echo "No old deployments to clean"
