name: Sync to OSS with Zero Downtime

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 15 # 设置最大运行时间为15分钟
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies and build
        run: |
          npm ci
          npm run docs:build

      - name: Install ossutil
        run: |
          curl -L https://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64 -o /usr/local/bin/ossutil
          chmod +x /usr/local/bin/ossutil

      - name: Generate unique deployment directory
        id: deployment
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "DEPLOY_DIR=deploy-$TIMESTAMP" >> $GITHUB_ENV

      - name: Upload new version to temp directory
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_SECRET }}
        run: |
          ossutil cp -r ./docs/.vuepress/dist/ oss://fromidea/$DEPLOY_DIR/ \
            --access-key-id=$ACCESS_KEY_ID \
            --access-key-secret=$ACCESS_KEY_SECRET \
            --endpoint=oss-cn-hangzhou.aliyuncs.com \
            --update

      - name: Update OSS routing configuration (atomic switch)
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_SECRET }}
        run: |
          # 创建并上传网站配置文件，将根请求重定向到新的部署目录
          cat > website_config.xml << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <WebsiteConfiguration>
            <IndexDocument>
              <Suffix>index.html</Suffix>
            </IndexDocument>
            <ErrorDocument>
              <Key>error.html</Key>
            </ErrorDocument>
            <RoutingRules>
              <RoutingRule>
                <Condition>
                  <KeyPrefixEquals>/</KeyPrefixEquals>
                </Condition>
                <Redirect>
                  <ReplaceKeyPrefixWith>$DEPLOY_DIR/</ReplaceKeyPrefixWith>
                </Redirect>
              </RoutingRule>
            </RoutingRules>
          </WebsiteConfiguration>
          EOF

          # 上传网站配置到OSS存储桶
          ossutil website -e oss-cn-hangzhou.aliyuncs.com \
            --access-key-id=$ACCESS_KEY_ID \
            --access-key-secret=$ACCESS_KEY_SECRET \
            --method put oss://fromidea website_config.xml

      - name: Clean up old deployments (keep latest 3)
        env:
          ACCESS_KEY_ID: ${{ secrets.OSS_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.OSS_SECRET }}
        run: |
          # 列出所有部署目录
          DEPLOY_DIRS=$(ossutil ls oss://fromidea/ \
            --access-key-id=$ACCESS_KEY_ID \
            --access-key-secret=$ACCESS_KEY_SECRET \
            --endpoint=oss-cn-hangzhou.aliyuncs.com | grep "deploy-" | sort -r)

          # 跳过最新的3个部署，删除其余的
          COUNT=0
          echo "$DEPLOY_DIRS" | while read -r LINE; do
            if [[ $LINE == *"deploy-"* ]]; then
              COUNT=$((COUNT+1))
              DIR=$(echo $LINE | awk '{print $NF}' | sed 's/oss:\/\/fromidea\///')
              if [ $COUNT -gt 3 ]; then
                echo "Removing old deployment: $DIR"
                ossutil rm -r oss://fromidea/$DIR/ \
                  --access-key-id=$ACCESS_KEY_ID \
                  --access-key-secret=$ACCESS_KEY_SECRET \
                  --endpoint=oss-cn-hangzhou.aliyuncs.com
              fi
            fi
          done
